# Step 1: Create IAM OIDC provider (if not already done)
# eksctl utils associate-iam-oidc-provider --cluster=langfuse-cluster --region=ap-south-1 --approve

# Step 2: Create IAM role and service account
# eksctl create iamserviceaccount \
#   --cluster=langfuse-cluster \
#   --namespace=kube-system \
#   --name=aws-load-balancer-controller \
#   --role-name=AmazonEKSLoadBalancerControllerRole-prod \
#   --attach-policy-arn=arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess \
#   --approve \
#   --region=ap-south-1

# Step 3: Install via Helm
# helm repo add eks https://aws.github.io/eks-charts
# helm repo update
# helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
#   -n kube-system \
#   --set clusterName=langfuse-cluster \
#   --set serviceAccount.create=false \
#   --set serviceAccount.name=aws-load-balancer-controller \
#   --set region=ap-south-1 \
#   --set vpcId=<YOUR_VPC_ID>

---
# ServiceAccount (created by eksctl iamserviceaccount command above)
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/AmazonEKSLoadBalancerControllerRole-prod
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: aws-load-balancer-controller
  namespace: kube-system
